name: Unit Tests

on:
  push:
    branches:
      - redo-ep2
  pull_request:
    branches: [redo-ep2]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install
          npm test
